// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5URMdLBdsUg94va6SV_7I3UAja6Hfyo',
    appId: '1:594283361767:web:5ef1002487251ef5e17942',
    messagingSenderId: '594283361767',
    projectId: 'getmarriedapp-810aa',
    authDomain: 'getmarriedapp-810aa.firebaseapp.com',
    databaseURL: 'https://getmarriedapp-810aa-default-rtdb.firebaseio.com',
    storageBucket: 'getmarriedapp-810aa.appspot.com',
    measurementId: 'G-DFC7KJDMMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqo0k8xh_cqUJ3VgbG52Bind--dTG8j8',
    appId: '1:594283361767:android:db16d6fee0f25331e17942',
    messagingSenderId: '594283361767',
    projectId: 'getmarriedapp-810aa',
    databaseURL: 'https://getmarriedapp-810aa-default-rtdb.firebaseio.com',
    storageBucket: 'getmarriedapp-810aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPczalQC0SE9a-bpV2EAJBQZW_A_6qvU0',
    appId: '1:594283361767:ios:cb7c2321e2f92f52e17942',
    messagingSenderId: '594283361767',
    projectId: 'getmarriedapp-810aa',
    databaseURL: 'https://getmarriedapp-810aa-default-rtdb.firebaseio.com',
    storageBucket: 'getmarriedapp-810aa.appspot.com',
    androidClientId: '594283361767-3kup8m02voek20k4fenigjvnl1eed0td.apps.googleusercontent.com',
    iosClientId: '594283361767-k88keavhjmcfor3nia01otlf1vs0edr9.apps.googleusercontent.com',
    iosBundleId: 'com.getmarriedapp',
  );
}
